import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/navbar";
import Footer from "./components/Footer";
import FloatingMailButton from "./components/contact/contact"; // 👈 Added Import
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Alladin.pk - SS Energy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        
        {children}

        {/* 👈 WhatsApp Floating Button Har Page par dikhega */}
        <FloatingMailButton />

        <Footer />
      </body>
    </html>
  );
}